# Model arguments
model_name_or_path: /home/jonathan_lu/research/alignment-handbook/tinyllama-lowercase-sft
tokenizer_name_or_path: /home/shared_models/huggingface/TinyLlama-1.1B-Chat-v1.0
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_r: 128
lora_alpha: 256
lora_dropout: 0.05
lora_target_modules: all-linear

# Data training arguments

dataset_mixer:
  jonluj/lowercase_ultrafeedback: 0.15
  jonluj/lowercase_ultrafeedback_with_reject: 0.15
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.03
do_eval: true
eval_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: jonluj/tiny-llama-lowercase
hub_private_repo: true
learning_rate: 5.0e-6
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1028
max_prompt_length: 584
num_train_epochs: 1
optim: paged_adamw_32bit
output_dir: outputs/tiny-llama-lowercase-sft_dpo-merged-mixed
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
push_to_hub: false
report_to: wandb
run_name: tiny-llama-lowercase-sft_dpo-merged-mixed
save_strategy: "steps"
save_steps: 100
seed: 42
warmup_ratio: 0.1